term.clear()

print("                    .MMM.")
print("                     .OMM")
print("                       MM?")
print("                      ~MMM                              .  ..")
print("                    =MM~MM8                    . :ZMMMMMMMMM:")
print("                   MM8  +MM.       . :OMMMMMMMD+....NMMD.  :MM")
print("                .MM8.    MMO .MMM8,.  .     .. NMMD..  MMMMMMM")
print("         .MMN  'MO       .MM.  ..MMM. .   OMMM . .?MMMMMMMMMMM")
print("    MMD=.  :M.  8.       .,ZM .MMM. .$MMM.... MMMMMMMMMMMMMMMM")
print("    MMMI.. ...  MM.. ....   .$ ..MMMO. ...MMMMMMMMMMMMMMMM7")
print("    MD .MMM8.. ...MMMM...   NMMO .   8MMMMMMMMMMMMMMMM .    IM")
print("    MD     ...ZMMMMMMMMMMMD.. ..~MMMMMMMMMMMMMMMM?.   ..MMMMMM")
print("    MD                    ..MMMMMMMMMMMMMMMMN .  . OMMMMMMMMMM")
print("    MD                   .MMMMMMMMMMMMMM8  .  .NMMMMMMMMMMMMMM")
print("    MD                   .MMMMMMMMMM. .   +MMMMMMMMMMMMMMMM~..")
print("    MD                   .MMMMMI.  .. MMMMMMMMMMMMMMMM8 ...,MM")
print("    MD                   .M.. .  ?MMMMMMMMMMMMMMMM.....DMMMMMM")
print("    MD                       $MMMMMMMMMMMMMMMM.. . MMMMMMMMMMM")
print("    MD                   .MMMMMMMMMMMMMMMI. ..7MMMMMMMMMMMMMMM")
print("    MD                   .MMMMMMMMMMM   . MMMMMMMMMMMMMMMM")
print("    MD                   .MMMMMM~ .  $MMMMMMMMMMMMMMMM")
print("    MD                   .MM,. ..8MMMMMMMMMMMMMMMM")
print("    MD                    ..:MMMMMMMMMMMMMMMM?")
print("    MM                   .MMMMMMMMMMMMMMN")
print("     MM                  .MMMMMMMMMM")
print("      .MMM=..            .MMMMMM")
print("          '77MMMMMMMMMMMMMM7")
print(" ")
print("The cake is a lie...")